# Generated by Django 3.1.13 on 2021-09-03 16:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('presentation', models.TextField(verbose_name='presentation')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('capacity', models.IntegerField(verbose_name='capacity')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='picture')),
                ('flyer', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='flyer')),
            ],
            options={
                'verbose_name': 'menus',
                'verbose_name_plural': 'menus',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('pax', models.IntegerField(verbose_name='pax')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('mobile', models.CharField(max_length=20, verbose_name='mobile')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='code')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu', verbose_name='menus')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'ordering': ['-date'],
            },
        ),
    ]
