# Generated by Django 3.1.13 on 2021-09-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_siteproperty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='code',
            new_name='uuid',
        ),
    ]
